portal_bancario/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from portal import views

urlpatterns = [
    path('', views.home, name=""),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include(('users.urls','users'), namespace='users')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from.views import signup, ActivateUser, templateEmailSent, UserList, UserApp, ProfileAPI, newAccount, getBadget, Movement, newMovement, deleteMovement, disableStateAccount

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>/', ActivateUser, name='activate'),
    path('emailsent/<str:username>/', templateEmailSent, name='emailsent'),
    path('listar/', UserList.as_view(), name="listar"),
    path('userapp/<pk>', UserApp, name="userapp"),
	path('api/', ProfileAPI.as_view(), name = "api"),
	path('api/<int:pk>', ProfileAPI.as_view(), name = "api"),
	path('newAccount/<pk>', newAccount, name = "newAccount"),
	path('getBadget/<int:pk>/<int:pk_user>', getBadget, name = "getBadget"),
	path('movement/<pk>', Movement, name = "movement"),
	path('newMovement/<pk_account>/<pk_balance>/<pk_user>', newMovement, name = "newMovement"),
	path('deleteMovement/<pk_account>/<pk_balance>/<pk_user>/<pk_movement>', deleteMovement, name = "deleteMovement"),
	path('disableStateAccount/<pk>/<account_number>/<creation_day>/<type_account>/<state_account>/<pk_user>', disableStateAccount, name = "disableStateAccount")
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}

<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
</head>

<body>
    <div class="container">
        <div>
            <div style="align-items: flex-start; margin-top: 10px">
                <nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding-bottom: 0px;padding-top: 0px; background-color: #ffffff !important; box-shadow: 1px 3px 6px 0px #c1baba; border-radius: 13px">
                    <a class="navbar-brand" href="#">
                        <img src="https://i.ibb.co/9gb7XZH/Logo.png" alt="" style="width: 93px">
                        <!-- <img src="{% static 'images/Logo.png' %}" alt="" style="width: 93px">
                    </a> -->
                    <a class="navbar-brand" href="{% url '' %}">Inicio</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            {% if user.profile.rol.descripcion == "Empleado" %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'users:listar' %}">Usuarios <span class="sr-only">(current)</span></a>
                            </li>
                            {% else %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'users:userapp' user.id %}">Administrar cuentas <span class="sr-only">(current)</span></a>
                            </li>
                            {% endif %}
                            <!-- <li class="nav-item active">
                                <a class="nav-link" href="{% url 'users:userapp' user.id %}">Ayuda <span class="sr-only">(current)</span></a>
                            </li> -->
                        </ul>
                        {% if user.is_authenticated %}
                        <h6 class="ml-5">Hola {{ user.username }}!</h6>
                        <a href="{% url 'logout' %}" class="btn btn-info ml-2">Cerrar Sesión</a>
                        {% else %}
                        <a href="{% url 'users:signup' %}" class="btn btn-light ml-5" style="background-color:#3173b5;border-color: #f8f9fa; color: white">Registrarse</a>
                        <a href="{% url 'login' %}" class="btn btn-danger ml-2">Iniciar Sesión</a>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>